openapi: 3.0.3
info:
  x-summary: 'Piattaforma Notifiche: API per il Front End delle PA'
  title: 'Gestione Api Key'
  version: '1.0.0'
tags:
  - name: ApiKeysPrvt
    description: >-
      Invocazioni utilizzabili dai mittenti per la gestione delle api keys
paths:
  "/api-key-prvt/api-keys/associate-api-key":
    post:
      summary: Cambia la virtual key di un api key dato un cxId
      description: >-
        servizio di cambio virtual key di un api key dato un cxId
      tags:
        - ApiKeysPrvt
      operationId: changeVirtualKeyApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestBodyApiKeyPk"
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Wrong state transition (i.e. enable an enabled key)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  schemas:
    RequestBodyApiKeyPk:
      title: Request cambio api key dato un cxId
      description: >-
        Assegnare al campo virtual key il nuovo valore da associare alla virtual key legata al xPagopaPnCxId
      type: object
      required:
        - xPagopaPnCxId
        - virtualKey
      properties:
        xPagopaPnCxId:
          type: string
          description: CxId dell'api key
        virtualKey:
          type: string
          description: Valore dell'api key

    Problem:
      type: object
      properties:
        status:
          type: integer
          description: Contiene il codice HTTP dell'errore
        title:
          type: string
        detail:
          type: string
        traceId:
          type: string
        timestamp:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              element:
                type: string
              detail:
                type: string

