AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Transform:
  - UpdateDeploymentTransform

Parameters:

  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  VpcEgressSubnetsIds:
    Type: String
    Description: subnets where to install PN-CORE

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  UsagePlanDefault:
    Type: String
    Description: 'Id Usage Plan default'

  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  PaAggregationsTableArn:
    Type: String
    Description: 'Arn of dynamodb table containing PaAggregations information'

  AggregatesTableArn:
    Type: String
    Description: 'Arn of dynamodb table containing Aggregates information'

  ApiKeyTableArn:
    Type: String
    Description: 'Arn of dynamodb table containing VirtualKey information'

  PublicKeyTableArn:
    Type: String
    Description: 'Arn of dynamodb table containing Public Key information'

  PaAggregationsTableName:
    Type: String
    Description: 'Name of dynamodb table containing aggregations'

  AggregatesTableName:
    Type: String
    Description: 'Name of dynamodb table containing aggregates'

  ApiKeyTableName:
    Type: String
    Description: 'Name of dynamodb table containing apikey'

  PublicKeyTableName:
    Type: String
    Description: 'Name of dynamodb table containing public keys'

  FlagPdnd:
    Type: String
    Description: 'Flag che definisce se la PA si deve integrare necessariamente con PDND Interoperabilità o meno'

  ApikeyManagerInternalQueueName:
    Type: String
    Description: 'Name of Internal queue'

  ApikeyManagerInternalQueueARN:
    Type: String
    Description: 'ARN for ApikeyManagerInternalQueue'

  ApikeyManagerInternalQueueDLQName:
    Type: String
    Description: 'Name of Internal queue DLQ'

  ApikeyManagerInternalQueueDLQARN:
    Type: String
    Description: 'ARN for ApikeyManagerInternalQueue DLQ'

  ApiKeyManagerPipeBatchSize:
    Type: Number
    Default: 30
    Description: records batch size of apikey manager pipe (DynamoDB to SQS)

  # OpenApi Bucket params
  MicroserviceBucketName:
    Type: String
    Default: ''
    Description: 'Name of the bucket where the microservice files are copied during deploy'

  MicroserviceBucketBaseKey:
    Type: String
    Default: ''
    Description: 'Base key of the microservice in the s3 bucket'

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 15
  
  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy. 
    Type: Number
    Default: 5
  
  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy. 
    Type: Number
    Default: 2

  HealthCheckPath:
    Type: String
    Default: '/actuator/health'

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String
  
  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks

  ApiKeyTablesEncryptKeyId:
    Type: String
    Description: 'KMS ID for apikey manager tables'

  # Log group parameters
  EcsLogGroup:
    Type: String
    Description: 'Ecs log group name'

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'

  WebWafLimit:
    Default: 6000
    Type: Number
    Description: web waf limit

  EnhancedWebSecurityEnabled:
    Type: String
    Default: false
    Description: Enable additional WAF Web rules
    AllowedValues:
      - true
      - false

Resources:

  # PN-ApiKey-Manager microservice
  ApikeyManagerMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        HealthCheckPath: !Ref HealthCheckPath
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        AutoscalingStrategy: REST-API
        MicroServiceUniqueName: !Sub '${ProjectName}-apikey-manager'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_APIKEY_MANAGER_AWS_USAGEPLAN_DEFAULT=${UsagePlanDefault}'
        ContainerEnvEntry3: !Sub 'PN_APIKEY_MANAGER_EXTERNAL_REGISTRIES_API_BASE_URL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry4: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
        ContainerEnvEntry5: !Sub 'PN_APIKEY_MANAGER_HEALTH_CHECK_PATH=${HealthCheckPath}'
        ContainerEnvEntry6: !Sub 'PN_APIKEY_MANAGER_FLAG_PDND=${FlagPdnd}'
        ContainerEnvEntry7: !Sub 'PN_APIKEY_MANAGER_SQS_INTERNALQUEUENAME=${ApikeyManagerInternalQueueName}'
        ContainerEnvEntry8: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${ApikeyManagerInternalQueueName}'

        MappedPaths: '/api-key-self/*,/api-key-bo/*,/api-key-prvt/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref VpcEgressSubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        TaskRoleManagedPolicyArn: !Ref ApikeyManagerMicroserviceTaskManagedPolicy
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy

  PgPublicKeyTtlPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt PnApiKeyManagerPipeExecutionRole.Arn
      Name: !Sub ${ProjectName}-apikey-manager-publickey-ttl-pipe
      Source: !GetAtt PublicKeyTable.StreamArn
      SourceParameters:
        DynamoDBStreamParameters:
          StartingPosition: TRIM_HORIZON
          BatchSize: !Ref ApiKeyManagerPipeBatchSize
      FilterCriteria:
        Filters:
          - Pattern: '{ "eventName": ["DELETE"] }'
      Target: !Ref ApikeyInternalQueueARN
      TargetParameters:
        InputTemplate: |
          {
            "cxId": <$.dynamodb.Keys.cxId.S>,
            "kid": <$.dynamodb.Keys.kid.S>,
            "action": "JWKS"
          }

  PgPublicKeyPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt PnApiKeyManagerPipeExecutionRole.Arn
      Name: !Sub ${ProjectName}-apikey-manager-publickey-pipe
      Source: !GetAtt PublicKeyTable.StreamArn
      SourceParameters:
        DynamoDBStreamParameters:
          StartingPosition: TRIM_HORIZON
          BatchSize: !Ref ApiKeyManagerPipeBatchSize
      FilterCriteria:
        Filters:
          - Pattern: '{ "eventName": ["INSERT", "MODIFY"] }'
      Target: !Ref ApikeyInternalQueueARN
      TargetParameters:
        InputTemplate: |
          {
            "cxId": <$.dynamodb.Keys.cxId.S>,
            "action": "JWKS"
          }

  PnApiKeyManagerPipeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-apikey-manager-publickey-source-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !Ref PublicKeyTableArn
        - PolicyName: !Sub ${ProjectName}-apikey-manager-publickey-target-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Ref ApikeyInternalQueueARN

  ApikeyManagerMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - apigateway:POST
              - apigateway:GET
            Resource:
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/apikeys'
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/usageplans'
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/usageplans/*'
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/usageplans/*/keys'
          - Effect: Allow
            Action:
              - apigateway:DELETE
            Resource:
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/apikeys/*'
              - !Sub 'arn:aws:apigateway:${AWS::Region}::/usageplans/*/keys/*'
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ExecuteTransaction
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:TransactGetItems
              - dynamodb:TransactWriteItems
              - dynamodb:UpdateItem
              - dynamodb:Scan
            Resource:
              - !Ref AggregatesTableArn
              - !Ref PaAggregationsTableArn
              - !Ref ApiKeyTableArn
              - !Ref PublicKeyTableArn
              - !Sub '${AggregatesTableArn}/index/*'
              - !Sub '${PaAggregationsTableArn}/index/*'
              - !Sub '${ApiKeyTableArn}/index/*'
              - !Sub '${PublicKeyTableArn}/index/*'
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
            Resource:
              - !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${ApiKeyTablesEncryptKeyId}
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:GetQueueUrl
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource:
              - !Ref ApikeyInternalQueueARN
              - !Ref ApikeyInternalQueueDLQARN

  ApiKeyManagerApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-apikey-manager'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'api-key-self'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn

  ApiKeyManagerApiGatewayWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-apikey-manager-self'
        IntendedUsage: WEB 
        APIGatewayARNs: !GetAtt ApiKeyManagerApiGateway.Outputs.APIGatewayARN
        Limit: !Ref WebWafLimit
        EnhancedWebSecurityEnabled: !Ref EnhancedWebSecurityEnabled

  ApiKeyManagerApiGatewayAggregate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-apikey-manager-bo'
        IntendedUsage: BACKOFFICE
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'api-key-bo'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        OpenApiBucketName: !Ref MicroserviceBucketName
        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/pn-apikey-manager-bo.yaml

  ApiKeyManagerApiGatewayAggregateWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-apikey-manager-bo'
        IntendedUsage: BACKOFFICE 
        APIGatewayARNs: !GetAtt ApiKeyManagerApiGatewayAggregate.Outputs.APIGatewayARN

  ApiKeyManagerApiGatewayPrvt:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-apikey-manager-prvt'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'api-key-prvt'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn

  ApiKeyManagerApiGatewayPrvtWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-apikey-manager-prvt'
        IntendedUsage: WEB 
        APIGatewayARNs: !GetAtt ApiKeyManagerApiGatewayPrvt.Outputs.APIGatewayARN
        EnhancedWebSecurityEnabled: !Ref EnhancedWebSecurityEnabled

  ApiKeyManagerMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-apikey-manager"
        DynamoDBTableNames: !Join
          - ','
          - - !Ref PaAggregationsTableName
            - !Ref AggregatesTableName
            - !Ref ApiKeyTableName
            - !Ref PublicKeyTableName
        RestApiStageArns: !Join
          - ','
          - - !GetAtt ApiKeyManagerApiGateway.Outputs.RestApiStageArn
            - !GetAtt ApiKeyManagerApiGatewayAggregate.Outputs.RestApiStageArn
        RestApiNames: !Join
          - ','
          - - !GetAtt ApiKeyManagerApiGateway.Outputs.RestApiName
            - !GetAtt ApiKeyManagerApiGatewayAggregate.Outputs.RestApiName
        QueueArns: !Join
          - ','
          - - !Ref ApikeyInternalQueueName
        AlarmArns: !Join
          - ','
          - - !GetAtt ApikeyManagerMicroservice.Outputs.FatalLogsMetricAlarmArn
            - !GetAtt ApiKeyManagerApiGateway.Outputs.RestApiErrorAlarmArn
            - !GetAtt ApiKeyManagerApiGateway.Outputs.RestApiLatencyAlarmArn
            - !GetAtt ApiKeyManagerApiGatewayAggregate.Outputs.RestApiErrorAlarmArn
            - !GetAtt ApiKeyManagerApiGatewayAggregate.Outputs.RestApiLatencyAlarmArn
        LogGroupsNames: !Join
          - ','
          - - !Sub '/aws/ecs/${ProjectName}-apikey-manager'    