AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'


Resources:
  ###      KEY PAIR PER CREARE JWT NECESSARIO PER ACCEDERE AI SERVIZI M2M DI PDND    ###
  ###   La chiave viene impiegata per firmare il client assertion che serve          ###
  ###   per richedere a PDND il JWT da utilizzare per invocare i servizi M2M di PDND ###
  ######################################################################################
  # Dynamo Table
  ApiKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-apiKey'
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "virtualKey"
          AttributeType: "S"
        - AttributeName: "lastUpdate"
          AttributeType: "S"
        - AttributeName: "x-pagopa-pn-cx-id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "virtualKey-id-index"
          KeySchema:
            - AttributeName: virtualKey
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "paId-lastUpdate-index"
          KeySchema:
            - AttributeName: x-pagopa-pn-cx-id
              KeyType: HASH
            - AttributeName: lastUpdate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: "PAY_PER_REQUEST"

  AggregatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-aggregates'
      AttributeDefinitions:
        - AttributeName: "aggregateId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "aggregateId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  PaAggregationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-paAggregations'
      AttributeDefinitions:
        - AttributeName: "x-pagopa-pn-cx-id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "x-pagopa-pn-cx-id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

#Necessario a causa di bug script deploy
Outputs:

  # Table parameters
  PaAggregationsTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of PaAggregationsTable
    Value: !Sub '${PaAggregationsTable.Arn}'

  AggregatesTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of AggregatesTable
    Value: !Sub '${AggregatesTable.Arn}'

  ApiKeyTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of ApiKeyTable
    Value: !Sub '${ApiKeyTable.Arn}'



